name: Build .NET MAUI Windows

on:
  push:
    branches: [ "GithubDeploy" ]
  pull_request:
    branches: [ "GithubDeploy" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x

    - name: Restore Dependencies
      run: dotnet restore DispatchesApp/DispatchesApp.csproj

    - name: Install MAUI workload
      run: dotnet workload install maui

    - name: Decrypt PFX File
      run: |
        echo "${{ secrets.WINDOWS_PFX_FILE }}" > cert.pfx.asc
        certutil -decode cert.pfx.asc cert.pfx

    - name: Add Cert to Store
      run: certutil -user -q -p ${{ secrets.WINDOWS_PFX_PASSWORD }} -importpfx cert.pfx NoRoot

    - name: Build
      run: dotnet publish DispatchesApp/DispatchesApp.csproj -c Release -f:net7.0-windows10.0.19041.0 /p:GenerateAppxPackageOnBuild=true /p:AppxPackageSigningEnabled=true /p:PackageCertificateThumbprint="${{ secrets.WINDOWS_PFX_THUMBPRINT }}" /p:RuntimeIdentifiers=win10-x64

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3.1.0
      with:
        path: .\**\AppPackages\**\*.*